jobs:
  include:

    - stage: GitSyntax
      language: bash
      script:
        - bash ./Infra/GitSyntax/Commits.sh
        - bash ./Infra/GitSyntax/Branch.sh

    - stage: Linting
      language: node_js
      node_js:
        - 10
      before_install:
        - npm install
      script:
        - bash ./Infra/Linters/Linting.sh